name: Data Migration Test

on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pytest mysql-connector-python dotenv sqlalchemy numpy pandas_gpt

    - name: Run tests
      run: pytest virtuous_interview/test.py
